server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=GMT
    username: root
    password: cyf123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update